version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weakly
    commit-message:
      prefix: ''
    labels: []
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weakly
    commit-message:
      prefix: ''
    labels: []
