//! An unbounded map of futures.

use alloc::sync::Arc;
use core::fmt::{self, Debug};
use core::hash::Hash;
use core::iter::FromIterator;
use core::pin::Pin;
use futures_core::future::Future;
use futures_core::stream::{FusedStream, Stream};
use futures_core::task::{Context, Poll};
use std::collections::HashSet;

mod iter;
use self::iter::Keys;
#[allow(unreachable_pub)] // https://github.com/rust-lang/rust/issues/102352
pub use self::iter::{IntoIter, Iter, IterMut, IterPinMut, IterPinRef};
use crate::stream::futures_unordered_internal::task::HashTask;

use super::futures_unordered_internal::{FuturesUnorderedInternal, ReleasesTask};

/// A map of futures which may complete in any order.
///
/// This structure is optimized to manage a large number of futures.
/// Futures managed by [`MappedFutures`] will only be polled when they
/// generate wake-up notifications. This reduces the required amount of work
/// needed to poll large numbers of futures.
///
/// [`MappedFutures`] can be filled by [`collect`](Iterator::collect)ing an
/// iterator of futures into a [`MappedFutures`], or by
/// [`insert`](MappedFutures::insert)ing futures onto an existing
/// [`MappedFutures`]. When new futures are added,
/// [`poll_next`](Stream::poll_next) must be called in order to begin receiving
/// wake-ups for new futures.
///
/// Note that you can create a ready-made [`MappedFutures`] via the
/// [`collect`](Iterator::collect) method, or you can start with an empty set
/// with the [`MappedFutures::new`] constructor.
#[must_use = "streams do nothing unless polled"]
pub struct MappedFutures<K: Hash + Eq, Fut> {
    inner: FuturesUnorderedInternal<K, Fut, TaskSet<K, Fut>>,
}

struct TaskSet<K: Hash + Eq, Fut> {
    inner: HashSet<HashTask<K, Fut>>,
}

impl<K: Debug + Hash + Eq, Fut> Debug for TaskSet<K, Fut> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "TaskSet {{ ... }}")
    }
}

impl<K: Hash + Eq, Fut> ReleasesTask<K> for TaskSet<K, Fut> {
    fn release_task(&mut self, key: &K) {
        self.inner.remove(key);
    }

    fn new() -> Self {
        Self { inner: HashSet::new() }
    }
}

unsafe impl<K: Hash + Eq, Fut: Send> Send for MappedFutures<K, Fut> {}
unsafe impl<K: Hash + Eq, Fut: Sync> Sync for MappedFutures<K, Fut> {}
impl<K: Hash + Eq, Fut> Unpin for MappedFutures<K, Fut> {}

// MappedFutures is implemented using two linked lists. One which links all
// futures managed by a `MappedFutures` and one that tracks futures that have
// been scheduled for polling. The first linked list allows for thread safe
// insertion of nodes at the head as well as forward iteration, but is otherwise
// not thread safe and is only accessed by the thread that owns the
// `MappedFutures` value for any other operations. The second linked list is
// an implementation of the intrusive MPSC queue algorithm described by
// 1024cores.net.
//
// When a future is submitted to the set, a task is allocated and inserted in
// both linked lists. The next call to `poll_next` will (eventually) see this
// task and call `poll` on the future.
//
// Before a managed future is polled, the current context's waker is replaced
// with one that is aware of the specific future being run. This ensures that
// wake-up notifications generated by that specific future are visible to
// `MappedFutures`. When a wake-up notification is received, the task is
// inserted into the ready to run queue, so that its future can be polled later.
//
// Each task is wrapped in an `Arc` and thereby atomically reference counted.
// Also, each task contains an `AtomicBool` which acts as a flag that indicates
// whether the task is currently inserted in the atomic queue. When a wake-up
// notification is received, the task will only be inserted into the ready to
// run queue if it isn't inserted already.

impl<K: Hash + Eq, Fut> Default for MappedFutures<K, Fut> {
    fn default() -> Self {
        Self::new()
    }
}

impl<K: Hash + Eq, Fut> MappedFutures<K, Fut> {
    /// Constructs a new, empty [`MappedFutures`].
    ///
    /// The returned [`MappedFutures`] does not contain any futures.
    /// In this state, [`MappedFutures::poll_next`](Stream::poll_next) will
    /// return [`Poll::Ready(None)`](Poll::Ready).
    pub fn new() -> Self {
        Self { inner: FuturesUnorderedInternal::new() }
    }

    /// Returns the number of futures contained in the set.
    ///
    /// This represents the total number of in-flight futures.
    pub fn len(&self) -> usize {
        self.inner.len()
    }

    /// Returns `true` if the set contains no futures.
    pub fn is_empty(&self) -> bool {
        // Relaxed ordering can be used here since we don't need to read from
        // the head pointer, only check whether it is null.
        self.inner.is_empty()
    }

    /// This is a code stank
    fn set(&mut self) -> &mut HashSet<HashTask<K, Fut>> {
        &mut self.inner.inner.inner
    }

    /// Insert a future into the set.
    ///
    /// This method adds the given future to the set. This method will not
    /// call [`poll`](core::future::Future::poll) on the submitted future. The caller must
    /// ensure that [`MappedFutures::poll_next`](Stream::poll_next) is called
    /// in order to receive wake-up notifications for the given future.
    ///
    /// This method will remove and drop a future that is already mapped to the provided key.
    /// Returns true if another future was not removed to make room for the provided future.
    pub fn insert(&mut self, key: K, future: Fut) -> bool {
        let replacing = self.cancel(&key);
        let task = self.inner.push(key, future);
        // self.inner.self.hash_set.insert(task.into());
        self.set().insert(task.into());
        !replacing
    }

    /// Insert a future into the set and return the displaced future, if there was one.
    ///
    /// This method adds the given future to the set. This method will not
    /// call [`poll`](core::future::Future::poll) on the submitted future. The caller must
    /// ensure that [`MappedFutures::poll_next`](Stream::poll_next) is called
    /// in order to receive wake-up notifications for the given future.
    /// Returns true if another future was ma
    pub fn replace(&mut self, key: K, future: Fut) -> Option<Fut>
    where
        Fut: Unpin,
    {
        let replacing = self.remove(&key);
        let task = self.inner.push(key, future);
        // self.hash_set.insert(task.into());
        self.set().insert(task.into());
        replacing
    }

    /// Remove a future from the set, dropping it.
    ///
    /// Returns true if a future was cancelled.
    pub fn cancel(&mut self, key: &K) -> bool {
        // if let Some(task) = self.hash_set.get(key) {
        if let Some(task) = self.set().take(key) {
            unsafe {
                if (*task.future.get()).is_some() {
                    *task.future.get() = None;
                    self.inner.unlink(Arc::as_ptr(&task.inner));
                    return true;
                }
            }
        }
        false
    }

    /// Remove a future from the set and return it.
    pub fn remove(&mut self, key: &K) -> Option<Fut>
    where
        Fut: Unpin,
    {
        // if let Some(task) = self.hash_set.get(key) {
        if let Some(task) = self.set().take(key) {
            unsafe {
                let fut = (*task.future.get()).take().unwrap();
                self.inner.unlink(Arc::as_ptr(&task.inner));
                return Some(fut);
            }
        }
        None
    }

    /// Returns `true` if the map contains a future for the specified key.
    pub fn contains(&mut self, key: &K) -> bool {
        self.set().contains(key)
    }

    /// Get a pinned mutable reference to the mapped future.
    pub fn get_pin_mut(&mut self, key: &K) -> Option<Pin<&mut Fut>> {
        // if let Some(task_ref) = self.hash_set.get(key) {
        if let Some(task_ref) = self.set().get(key) {
            unsafe {
                if let Some(fut) = &mut *task_ref.inner.future.get() {
                    return Some(Pin::new_unchecked(fut));
                }
            }
        }
        None
    }

    /// Get a pinned mutable reference to the mapped future.
    pub fn get_mut(&mut self, key: &K) -> Option<&mut Fut>
    where
        Fut: Unpin,
    {
        // if let Some(task_ref) = self.hash_set.get(key) {
        if let Some(task_ref) = self.set().get(key) {
            unsafe {
                if let Some(fut) = &mut *task_ref.inner.future.get() {
                    return Some(fut);
                }
            }
        }
        None
    }

    /// Get a shared reference to the mapped future.
    pub fn get(&mut self, key: &K) -> Option<&Fut> {
        // if let Some(task_ref) = self.hash_set.get(key) {
        if let Some(task_ref) = self.set().get(key) {
            unsafe {
                if let Some(fut) = &*task_ref.inner.future.get() {
                    return Some(fut);
                }
            }
        }
        None
    }

    /// Get a pinned shared reference to the mapped future.
    pub fn get_pin(&mut self, key: &K) -> Option<Pin<&Fut>> {
        // if let Some(task_ref) = self.hash_set.get(key) {
        if let Some(task_ref) = self.set().get(key) {
            unsafe {
                if let Some(fut) = &*task_ref.future.get() {
                    return Some(Pin::new_unchecked(fut));
                }
            }
        }
        None
    }

    /// Returns an iterator of keys in the mapping.
    pub fn keys<'a>(&'a self) -> Keys<'a, K, Fut> {
        Keys {
            // inner: self.hash_set.iter().map(Box::new(|hash_task| HashTask::key_unwrap(hash_task))),
            // inner: self.set().iter().map(Box::new(|hash_task| HashTask::key_unwrap(hash_task))),
            // inner: self.set().keys(),
            inner: Pin::new(&self.inner).iter_pin_ref(),
        }
    }

    /// Returns an iterator that allows inspecting each future in the set.
    pub fn iter(&self) -> Iter<'_, K, Fut>
    where
        Fut: Unpin,
    {
        Iter(Pin::new(self).iter_pin_ref())
    }

    /// Returns an iterator that allows inspecting each future in the set.
    pub fn iter_pin_ref(self: Pin<&Self>) -> IterPinRef<'_, K, Fut> {
        // let (task, len) = self.atomic_load_head_and_len_all();
        // let pending_next_all = self.pending_next_all();

        // IterPinRef { task, len, pending_next_all, _marker: PhantomData }
        IterPinRef { inner: unsafe { self.map_unchecked(|thing| &thing.inner) }.iter_pin_ref() }
        // IterPinRef { task: (), len: (), pending_next_all: (), _marker: () }
    }

    /// Returns an iterator that allows modifying each future in the set.
    pub fn iter_mut(&mut self) -> IterMut<'_, K, Fut>
    where
        Fut: Unpin,
    {
        IterMut(Pin::new(self).iter_pin_mut())
    }

    /// Returns an iterator that allows modifying each future in the set.
    pub fn iter_pin_mut(self: Pin<&mut Self>) -> IterPinMut<'_, K, Fut> {
        // `head_all` can be accessed directly and we don't need to spin on
        // `Task::next_all` since we have exclusive access to the set.

        // IterPinMut { inner: Pin::new(&mut self.inner).iter_pin_mut() }
        IterPinMut {
            inner: unsafe { self.map_unchecked_mut(|thing| &mut thing.inner) }.iter_pin_mut(),
        }
        // IterPinMut { task, len, _marker: PhantomData }
    }
}

impl<K: Hash + Eq, Fut: Future> Stream for MappedFutures<K, Fut> {
    type Item = (K, Fut::Output);

    fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        match std::task::ready!(Pin::new(&mut self.inner).poll_next(cx)) {
            Some((task, output)) => {
                // let key = (*(**task).key.get()).take().unwrap();
                // let key = task.take_key();
                // MappedFutures::set(self.get_mut()).remove(&key);
                MappedFutures::set(self.get_mut()).remove(task.key().unwrap());
                return Poll::Ready(Some((task.take_key(), output)));
            }
            None => Poll::Ready(None),
        }
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let len = self.len();
        (len, Some(len))
    }
}

impl<K: Hash + Eq, Fut> Debug for MappedFutures<K, Fut> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "MappedFutures {{ ... }}")
    }
}

impl<K: Hash + Eq, Fut> MappedFutures<K, Fut> {
    /// Clears the set, removing all futures.
    pub fn clear(&mut self) {
        self.inner.clear();
        self.set().clear();
    }
}

impl<'a, K: Hash + Eq, Fut: Unpin> IntoIterator for &'a MappedFutures<K, Fut> {
    type Item = (&'a K, &'a Fut);
    type IntoIter = Iter<'a, K, Fut>;

    fn into_iter(self) -> Self::IntoIter {
        self.iter()
    }
}

impl<'a, K: Hash + Eq, Fut: Unpin> IntoIterator for &'a mut MappedFutures<K, Fut> {
    type Item = (&'a K, &'a mut Fut);
    type IntoIter = IterMut<'a, K, Fut>;

    fn into_iter(self) -> Self::IntoIter {
        self.iter_mut()
    }
}

impl<K: Hash + Eq, Fut: Unpin> IntoIterator for MappedFutures<K, Fut> {
    type Item = (K, Fut);
    type IntoIter = IntoIter<K, Fut>;

    fn into_iter(self) -> Self::IntoIter {
        IntoIter { inner: self.inner.into_iter() }
    }
}

impl<K: Hash + Eq, Fut> FromIterator<(K, Fut)> for MappedFutures<K, Fut> {
    fn from_iter<I>(iter: I) -> Self
    where
        I: IntoIterator<Item = (K, Fut)>,
    {
        let acc = Self::new();
        iter.into_iter().fold(acc, |mut acc, (key, item)| {
            acc.insert(key, item);
            acc
        })
    }
}

impl<K: Hash + Eq, Fut: Future> FusedStream for MappedFutures<K, Fut> {
    fn is_terminated(&self) -> bool {
        self.inner.is_terminated()
    }
}

impl<K: Hash + Eq, Fut> Extend<(K, Fut)> for MappedFutures<K, Fut> {
    fn extend<I>(&mut self, iter: I)
    where
        I: IntoIterator<Item = (K, Fut)>,
    {
        for (key, item) in iter {
            self.insert(key, item);
        }
    }
}

#[cfg(test)]
pub mod tests {
    use crate::stream::*;
    use futures::executor::block_on;
    use futures::future::LocalBoxFuture;
    use futures_timer::Delay;
    // use futures_util::StreamExt;
    // use crate::StreamExt;
    use std::boxed::Box;
    use std::time::Duration;

    fn insert_millis(futs: &mut MappedFutures<u32, Delay>, key: u32, millis: u64) {
        futs.insert(key, Delay::new(Duration::from_millis(millis)));
    }

    fn insert_millis_pinned(
        futs: &mut MappedFutures<u32, LocalBoxFuture<'static, ()>>,
        key: u32,
        millis: u64,
    ) {
        futs.insert(key, Box::pin(Delay::new(Duration::from_millis(millis))));
    }

    #[test]
    fn map_futures() {
        let mut futures: MappedFutures<u32, Delay> = MappedFutures::new();
        insert_millis(&mut futures, 1, 50);
        insert_millis(&mut futures, 2, 50);
        insert_millis(&mut futures, 3, 150);
        insert_millis(&mut futures, 4, 200);

        assert_eq!(block_on(futures.next()).unwrap().0, 1);
        assert_eq!(futures.cancel(&3), true);
        assert_eq!(block_on(futures.next()).unwrap().0, 2);
        assert_eq!(block_on(futures.next()).unwrap().0, 4);
        assert_eq!(block_on(futures.next()), None);
    }

    #[test]
    fn remove_pinned() {
        let mut futures: MappedFutures<u32, LocalBoxFuture<'static, ()>> = MappedFutures::new();
        insert_millis_pinned(&mut futures, 1, 50);
        insert_millis_pinned(&mut futures, 3, 150);
        insert_millis_pinned(&mut futures, 4, 200);

        assert_eq!(block_on(futures.next()).unwrap().0, 1);
        assert_eq!(block_on(futures.remove(&3).unwrap()), ());
        insert_millis_pinned(&mut futures, 2, 60);
        assert_eq!(block_on(futures.next()).unwrap().0, 4);
        assert_eq!(block_on(futures.next()).unwrap().0, 2);
        assert_eq!(block_on(futures.next()), None);
    }

    #[test]
    fn mutate() {
        let mut futures: MappedFutures<u32, Delay> = MappedFutures::new();
        insert_millis(&mut futures, 1, 50);
        insert_millis(&mut futures, 2, 100);
        insert_millis(&mut futures, 3, 150);
        insert_millis(&mut futures, 4, 200);

        assert_eq!(block_on(futures.next()).unwrap().0, 1);
        futures.get_mut(&3).unwrap().reset(Duration::from_millis(30));
        assert_eq!(block_on(futures.next()).unwrap().0, 3);
        assert_eq!(block_on(futures.next()).unwrap().0, 2);
        assert_eq!(block_on(futures.next()).unwrap().0, 4);
        assert_eq!(block_on(futures.next()), None);
    }
}
